config/routes.rb
Rails.application.routes.draw do
  get '/sitemap.xml.gz', to: redirect("https://rrmsitemaps.s3.us-east-2.amazonaws.com/sitemap.xml.gz")

  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", invitations: 'invitations' }

  root to: 'customer_portal#index'

  post 'uploader/image', to: 'uploader#image' #add upload image to notams

  authenticated :user do
    resources :users, only: [:index]
    resource :profile_image, only: [:destroy]
    resources :accounts do
      post :invite_user, on: :member
      get 'users', to: 'accounts#users', as: :users
      resources :onboardings
      resource :logo, only: [:destroy]
      resources :tickets do
        member do
          patch :update_completed
        end
        resources :comments
        resources :ticket_subscriptions, only: [:create, :destroy]
      end
    end
    resources :tickets, only: [:index], controller: 'customer_portal/tickets'
  end

  get 'locations/states', to: 'locations#states'
  get 'locations/cities', to: 'locations#cities'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  delegate :account, to: :notifiable

  scope :unread, -> { where(read_at: nil) }

  broadcasts_to ->(notification) { "notifications" }, inserts_by: :prepend
  
  def mark_as_read!
    update(read_at: Time.current)
  end
end

app/views/notifications/_notification.html.erb
<%= link_to account_ticket_path(notification.account, notification.notifiable), data: { turbo_frame: "_top" } do %>
  <p class="py-2 px-4 hover:bg-blue-400 whitespace-nowrap <%= notification.read_at ? "bg-white" : "bg-yellow-100" %>"><%= notification.actor.first_name %> <%= notification.action %> <%= notification.notifiable.class.name.downcase %>: <%= notification.notifiable.title %></p>
<% end %>