config/routes.rb
Rails.application.routes.draw do
  get '/sitemap.xml.gz', to: redirect("https://rrmsitemaps.s3.us-east-2.amazonaws.com/sitemap.xml.gz")

  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", invitations: 'invitations' }

  root to: 'customer_portal#index'

  post 'uploader/image', to: 'uploader#image' #add upload image to notams

  authenticated :user do
    resources :users, only: [:index]
    resource :profile_image, only: [:destroy]
    resources :accounts do
      post :invite_user, on: :member
      get 'users', to: 'accounts#users', as: :users
      resources :onboardings
      resource :logo, only: [:destroy]
      resources :tickets do
        member do
          patch :update_completed
        end
        resources :comments
        resources :ticket_subscriptions, only: [:create, :destroy]
      end
    end
    resources :tickets, only: [:index], controller: 'customer_portal/tickets'
  end

  get 'locations/states', to: 'locations#states'
  get 'locations/cities', to: 'locations#cities'
end

app/views/shared/_blake_case_study.html.erb
<section class="flex lg:flex-row flex-col-reverse bg-gradient-to-b from-blue-900 to-blue-950 text-slate-50">
  <div class="flex flex-col items-center justify-center lg:w-1/2 py-10 lg:py-0">
    <%= image_tag "simplifly_500.webp", alt: "SimpliFly Logo", class: "w-1/2 py-10"%>
  </div>
  <div class="flex flex-col items-center justify-center lg:w-1/2 p-5">
    <h2 class="text-5xl font-semibold italic font-serif pt-10 lg:pt-0">CASE STUDY</h2>
    <p class="py-10 lg:mx-20">
      Introducing SimpliFly.  A flight school in the highly competitive area of Mesa, AZ.
    </p>
    <h3 class="lg:mx-20 font-semibold text-xl italic">
      We helped SimpliFly 10X the amount of leads coming to their school so they can train more pilots and expand their fleet.
    </h3>
  </div>
</section>
<section class="flex flex-col items-center bg-gradient-to-b from-white to-blue-200">
    <div class="max-w-3xl px-5 pt-20 ">
      <h4 class="text-5xl font-bold italic text-center pb-10">The Challenge</h4>
      <p class="pb-10">
        When Blake from SimpliFly gave Right Rudder Marketing a call, they were looking to update their website and get more leads coming into their school to increase their revenue.  They had a WordPress website already built out, social media profiles, and a GMB listing, but they weren't seeing much progress in their online rankings.
        With multiple flight schools at their airport competing for prospective students' attention, Blake knew he needed to do something about his digital marketing.  They were ranking way below the first page of search and on the Google Map listings they were #14, well below the view so 
        potential customers had difficulty even knowing they existed.
      </p>
      <p>
        SimpliFly was using a local agency that wasn't specialized for flight schools and aviation businesses.  There was a lot of friction in communication as the SimpliFly team had to describe the pilot training process and how aviation works.  
        They spent a lot of time going back and forth with their previous agency to get things sounding right because the previous agency didn't understand pilots.
      </p>
      <h4 class="text-5xl font-bold italic text-center py-10">What We Did</h4>
      <p>
        The first thing we did was research the local area and their competition.  With so many flight schools in their area, we had to understand what keywords were being searched for and then come up with a strategy to really accelerate their growth.
        We created an <%= link_to "awesome website", website_path, class: "text-blue-800 hover:underline"%> for them which really highlighted their main program: accelerated pilot training.
        We used target keywords in their website and GMB profile to really take things up a notch and we've seen great results.
      </p>
      <h4 class="text-5xl font-bold italic text-center py-10">The Results</h4>
        They are now getting flooded with inquiries and phone calls asking about their flight school.  
        They're ranking on the <b>first page</b> of Google Search and Google Maps.

      <div class="w-full flex flex-col items-center py-10">
        <%= image_tag "simplifly-heat-map-before-after.webp", class: "", alt: "Heatmap showing SimpliFly's ranking around their airport"%>
        <p class="text-slate-600 italic text-base">
          Heatmap showing SimpliFly's ranking around their airport
        </p>
      </div>
      <p class="pb-10">
        Our focus now is looking at where they are ranking as #4.  This is important because Google's first page listings only contain three businesses.  
        When we get a flight school to rank as #3 or higher, their business exponentially increases.
      </p>

      <div class="w-full flex flex-col items-center lg:pb-10">
        <iframe
            class="h-screen-1/3 lg:h-screen-1/2  aspect-video w-full lg:w-3/4"
            style=""
            src="https://tube.rvere.com/embed?v=qzT8Q49ExUw"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen>
        </iframe>
      </div>

      <!--Testimonial-->
      <div class="flex flex-col lg:flex-row py-10">
        <div class="lg:w-1/2 flex flex-col items-center">
          <%= image_tag "blake-simplifly.webp", class: "rounded-full w-1/2 mb-10 lg:mb-0", alt: "Blake"%>
        </div>
        <div class="lg:w-1/2">
          <p class="italic text-slate-800">
            "Right rudder marketing has been a huge help and blessing in our business. They made an amazing website for us.  They also understand aviation and pilots which is a huge help. If you own a flight school then you definitely need to use Right Rudder Marketing."
            <br><br>
            -Blake, Owner at SimpliFly
          </p>
        </div>
      </div>


    </div>
  </section>

app/views/shared/_copyright_social_footer.html.erb
<!--Copyright and social-->
<section class="bg-slate-700 text-slate-300 py-5 lg:pl-9 text-center lg:text-left flex flex-col-reverse lg:flex-col-reverse lg:justify-between lg:items-start">
  <div>
    <!--Desktop-->
    <div class="hidden lg:block">
      Copyright <%= Date.today.year %> <%=link_to root_path, class: "hover:underline" do%>Right Rudder Marketing LLC<%end%>.  All Rights Reserved.
    </div>
    <!--Mobile-->
    <div class="lg:hidden">
      Copyright <%= Date.today.year %> <%=link_to root_path, class: "hover:underline" do%>Right Rudder Marketing LLC<%end%>.  <br>All Rights Reserved.
    </div> 
    <div class="">
      <%=link_to privacy_policy_path, data: { turbo: false }, class: "hover:underline" do%>Privacy Policy<%end%> | <%= link_to terms_of_service_path, data: { turbo: false }, class: "hover:underline" do%>Terms of Service<%end%>
    </div>
  </div>
  <div class="flex flex-row justify-center gap-5 lg:gap-3 pb-3">
    <div class="hover:underline">
      <%=link_to "https://wa.me/13143582100", target: :blank do%>
        <%= image_tag "whatsappicon.webp", alt: "whatsapp icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.facebook.com/rightruddermarketing", target: :blank do%>
        <%= image_tag "facebookicon.webp", alt:"facebook icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.instagram.com/rightruddermarketing/", target: :blank do%>
        <%= image_tag "instagramicon.webp", alt:"instagram icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://www.youtube.com/@rightruddermarketing", target: :blank do%>
        <%= image_tag "youtubeicon.webp", alt:"youtube icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "https://twitter.com/rightruddermktg", target: :blank do%>  
        <%= image_tag "twittericon.webp", alt:"twitter icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
    <div class="hover:underline">
      <%=link_to "http://linkedin.com/company/rightruddermarketing", target: :blank do%>
        <%= image_tag "linkedinicon.webp", alt:"linkedin icon", class: "invert hover:scale-125 transition-all duration-300"%>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_cta1.html.erb
<section class="w-full h-screen bg-head bg-cover bg-center flex justify-center items-center">
  <div class="flex flex-col justify-center items-center drop-shadow-2xl">
      <h2 class="w-4/5 font-bold text-3xl sm:text-5xl lg:text-7xl"><span class="text-blue-800">Fly with digital marketing experts</span> that know the flight training industry.</h2>
      <p class="w-4/5 py-5 lg:py-10 lg:text-2xl font-semibold">We are a team of pilots that know the flight training industry.  Because if your marketing team doesn't know what the pilot training experience is like, then how can they be successful for you? See what we're talking about by booking a call now!</p>
      <%= link_to "Book a Strategy Call", schedule_call_path, class: "font-semibold bg-orange-500 hover:bg-orange-600 transition-all duration-300 text-xl text-white rounded-lg text-center py-2 px-5 lg:ml-8 lg:mr-2" %>
  </div>
</section>

app/views/shared/_ghl_chat.html.erb
<% if !current_page?(root_path) %>
<chat-widget
  location-id="Tg7heLI3UCqo8uRITWhZ"
  style="--chat-widget-primary-color: #3771C8; --chat-widget-active-color:#3771C8 ;--chat-widget-bubble-color: #3771C8 ;"
  sub-heading="Enter your question below and a Right Rudder Marketing team member will get right back to you." 
  use-email-field="true" 
  success-msg="One of our team members will contact you shortly." 
  prompt-avatar="https://firebasestorage.googleapis.com/v0/b/highlevel-backend.appspot.com/o/locationPhotos%2FTg7heLI3UCqo8uRITWhZ%2Fchat-widget-person?alt=media&token=79f20111-55b6-49b2-922c-9f14d8f73d3c" 
  agency-name="Right Rudder Marketing" 
  agency-website="https://rightruddermarketing.com" 
  locale="en-us" 
  primary-color="#3771C8"
  >
</chat-widget>
 <script
  src="https://widgets.leadconnectorhq.com/loader.js" 
  data-resources-url="https://widgets.leadconnectorhq.com/chat-widget/loader.js" >
 </script>
 <%end%>

app/views/shared/_nav.html.erb
<nav class="flex flex-1 flex-col">
  <% if current_user.admin? %>
    <%= select_tag('account', options_from_collection_for_select(Account.all, 'random_id', 'name',  account&.random_id), prompt: "Select an account", class: "mb-5 py-4 rounded-md border-gray-300", data: { controller: "account-select", account_select_target: "select", selected_account_id: account&.random_id }) %>
  <% end %>
  <ul role="list" class="flex flex-1 flex-col gap-y-7">
    <li>
      <ul role="list" class="-mx-2 space-y-1">
        <% if params[:id] || params[:account_id] %>
          <li>
            <%= link_to account_path(account), class: "group flex gap-x-3 rounded-md #{current_page?(account_path(account)) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>          
              <svg class="h-6 w-6 shrink-0 <%= current_page?(account_path(account)) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
              </svg>
              Dashboard
            <% end %>
          </li>
          <li>
            <%= link_to account_onboardings_path(account), class: "group flex gap-x-3 rounded-md #{current_page?(account_onboardings_path(account)) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>
              <svg class="h-6 w-6 shrink-0 <%= current_page?(account_onboardings_path(account)) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" viewBox="0 0 24 24"><path fill="currentColor" d="M11 15h6v2h-6zM9 7H7v2h2zm2 6h6v-2h-6zm0-4h6V7h-6zm-2 2H7v2h2zm12-6v14c0 1.1-.9 2-2 2H5c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2h14c1.1 0 2 .9 2 2m-2 0H5v14h14zM9 15H7v2h2z"/></svg>
              Onboarding
            <% end %>
          </li>
          <li>
            <%= link_to account_tickets_path(account), class: "group flex gap-x-3 rounded-md #{request.path.include?('/tickets') ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>
              <svg class="h-6 w-6 shrink-0 <%= request.path.include?('/tickets') ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
              </svg>
              Squawks
            <% end %>
          </li>
          <li>
            <%= link_to account_users_path(account), class: "group flex gap-x-3 rounded-md #{current_page?(account_users_path(account)) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>
              <svg class="h-6 w-6 shrink-0 <%= current_page?(account_users_path(account)) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
              </svg>
              Users
            <% end %>
          </li>
        <% elsif current_page?(edit_user_registration_path) %>
          <%= link_to 'Back', request.referer || root_path %>
        <% else %>
          <li>
            <!-- Current: "bg-gray-50 text-blue-600", Default: "text-gray-700 hover:text-blue-600 hover:bg-gray-50" -->
            <%= link_to root_path, class: "group flex gap-x-3 rounded-md #{current_page?(root_path) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>          
              <svg class="h-6 w-6 shrink-0 <%= current_page?(root_path) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
              </svg>
              Dashboard
            <% end %>
          </li>
          <li>
            <%= link_to accounts_path, class: "group flex gap-x-3 rounded-md #{current_page?(accounts_path) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>
              <svg class="h-6 w-6 shrink-0 <%= current_page?(accounts_path) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
              </svg>
              Accounts
            <% end %>
          </li>
          <li>
            <%= link_to tickets_path, class: "group flex gap-x-3 rounded-md #{current_page?(tickets_path) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>
              <svg class="h-6 w-6 shrink-0 <%= request.path.include?('/tickets') ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
              </svg>
              All Squawks
            <% end %>
          </li>
        <% end %>
        <!---
        <li>
          <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-blue-600">
            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-blue-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
            </svg>
            Calendar
          </a>
        </li>
        <li>
          <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-blue-600">
            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-blue-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5a3.375 3.375 0 00-3.375-3.375H9.75" />
            </svg>
            Documents
          </a>
        </li>
        <li>
          <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-blue-600">
            <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-blue-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6a7.5 7.5 0 107.5 7.5h-7.5V6z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 10.5H21A7.5 7.5 0 0013.5 3v7.5z" />
            </svg>
            Reports
          </a>
        </li>
        -->
      </ul>
    </li>
    <li class="mt-auto">
      <% if (params[:id] || params[:account_id]) && current_user.admin? %>
        <%= link_to root_path, class: "group -mx-2 flex gap-x-3 rounded-md #{current_page?(root_path) ? "bg-gray-50 text-blue-600" : "text-gray-700 hover:text-blue-600 hover:bg-gray-50"} p-2 text-sm font-semibold leading-6" do %>          
          <svg class="h-6 w-6 shrink-0 rotate-180 <%= current_page?(root_path) ? "text-blue-600" : "text-gray-400 group-hover:text-blue-600" %>" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 4.001H5v14a2 2 0 0 0 2 2h8m1-5l3-3m0 0l-3-3m3 3H9"/></svg>
          Back to Agency Dashboard
        <% end %>
      <% end %>
      <!---
      <a href="#" class="group -mx-2 flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-blue-600">
        <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-blue-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        Settings
      </a>
      -->
    </li>
  </ul>
</nav>

app/views/shared/_user_menu.html.erb
<div x-data="{ usermenu: false }" class="font-mono ">
  <div class="w-full lg:h-10 h-16 bg-slate-700 flex flex-row justify-between items-center sticky z-50">
    <div class="pl-5 text-slate-100">
      Welcome, <%= current_user.username %>
    </div>

    <!--Hamburger button-->
    <button @click="usermenu = ! usermenu;" class="text-slate-500 text-4xl pr-5 pb-1 hover:text-slate-800 lg:hidden">
      ☰
    </button >
    
    <!--desktop menu-->
    <div class="hidden lg:flex lg:flex-row lg:pr-10 xl:pr-5">
      <!--Button-->
      <% if current_user.admin? %>
        <%= button_to 'Customer Portal', root_path, method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <% elsif current_user.user? && current_user.account_users.any? %>
        <%= button_to 'Customer Portal', account_path(current_user.account_users.first.account), method: :get, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
      <% end %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "text-center block mr-5 text-slate-200 rounded-lg hover:underline" %>
    </div>
  </div>

    <!--Mobile Menu--->
    <div x-cloak x-show="usermenu" x-transition.duration.200ms class="bg-slate-700 flex flex-col justify-start items-center pb-10 z-50">
      <!--Spacer-->
      <div class="h-12"></div>
      <% if current_user.admin? %>
        <%= button_to 'Customer Portal', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <% elsif current_user.user? && current_user.account_users.any? %>
        <%= button_to 'Customer Portal', account_path(current_user.account_users.first.account), method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <% end %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>

    <!--Close button-->
    <button @click="usermenu = ! usermenu;" class="leading-10 text-slate-100 hover:text-slate-400 hover:bg-slate-700 border-2 hover:border-slate-400 w-min mt-5 px-5 rounded-full py-1">
      X
    </button>

    </div>
  </div>