config/routes.rb
Rails.application.routes.draw do
  get '/sitemap.xml.gz', to: redirect("https://rrmsitemaps.s3.us-east-2.amazonaws.com/sitemap.xml.gz")

  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", invitations: 'invitations' }

  root to: 'customer_portal#index'

  post 'uploader/image', to: 'uploader#image' #add upload image to notams

  authenticated :user do
    resources :users, only: [:index]
    resource :profile_image, only: [:destroy]
    resources :accounts do
      post :invite_user, on: :member
      get 'users', to: 'accounts#users', as: :users
      resources :onboardings
      resource :logo, only: [:destroy]
      resources :tickets do
        member do
          patch :update_completed
        end
        resources :comments
        resources :ticket_subscriptions, only: [:create, :destroy]
      end
    end
    resources :tickets, only: [:index], controller: 'customer_portal/tickets'
  end

  get 'locations/states', to: 'locations#states'
  get 'locations/cities', to: 'locations#cities'
end

app/models/onboarding.rb
class Onboarding < ApplicationRecord
  belongs_to :account
  validates :account_id, uniqueness: true

  store_accessor :primary_contact_information, :name, :email, :phone, :home_address
  store_accessor :specific_business_information, :hours_of_operation, :creation_date, :business_type, :core_values, :number_of_locations, :primary_service_areas, :secondary_service_areas, :number_of_employees, :summary_of_history, :unique_selling_proposition, :unique_training_programs_proposition
end

app/controllers/onboardings_controller.rb
class OnboardingsController < ApplicationController
  before_action :set_onboarding, only: %i[show edit update destroy]
  before_action :set_account

  def index
  end

  def new
    @onboarding = Onboarding.new
  end

  def create
    @onboarding = Onboarding.new(onboarding_params)
    
    respond_to do |format|
      if @onboarding.save
        format.html { redirect_to account_onboardings_url(@account), notice: 'Onboarding was successfully created.' }
        format.json { render :show, status: :created, location: @onboarding }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onboarding.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @onboarding.update(onboarding_params)
        format.html { redirect_to account_onboardings_url(@account), notice: 'Onboarding was successfully updated.' }
        format.json { render :show, status: :ok, location: @onboarding }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onboarding.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_onboarding
    @onboarding = Onboarding.find(params[:id])
  end

  def onboarding_params
    params.require(:onboarding).permit(
      :account_id,
      :name, :email, :phone, :home_address,
      :hours_of_operation, :creation_date, :business_type, :core_values, :number_of_locations, :primary_service_areas, :secondary_service_areas, :number_of_employees, :summary_of_history, :unique_selling_proposition, :unique_training_programs_proposition,
    )
  end

  def set_account
    @account = Account.findr(params[:account_id])
  end
end

app/helpers/onboardings_helper.rb
module OnboardingsHelper

  ONBOARDING_FIELDS = {
    primary_contact_information: {
      name: :string,
      email: :email,
      phone: :phone,
      home_address: :string,
    },
    specific_business_information: {
      hours_of_operation: :text,
      creation_date: :date,
      business_type: :string,
      core_values: :text,
      number_of_locations: :integer,
      primary_service_areas: :text,
      secondary_service_areas: :text,
      number_of_employees: :integer,
      summary_of_history: :text,
      unique_selling_proposition: :text,
      unique_training_programs_proposition: :text,
    },
    # training_programs: {},
    # team_members: {},

  }

  ONBOARDING_FIELD_LABELS = {
    name: "This will be the primary point of contact on your account",
    email: "We will use this email for all communications",
    phone: "What phone number should the Right Rudder Team use to reach you?",
    home_address: "We're sending you a welcome package!",

    hours_of_operation: "Ex: Mon-Fri 8am-6pm",
    creation_date: "When was your business founded?",
    business_type: "Ex: LLC, Corporation, Sole Proprietorship",
    core_values: "List your company's core values.",
    number_of_locations: "How many locations do you have?",
    primary_service_areas: "Order By Importance: Please enter cities, NOT counties or townships.",
    secondary_service_areas: "Order By Importance: Please enter cities, NOT counties or townships.",
    number_of_employees: "How many employees do you have?",
    summary_of_history: "Please provide a brief summary of how your flight school came into being",
    unique_selling_proposition: "What makes your flight school business special and different compared to other flight schools?",
    unique_training_programs_proposition: "Please let us know anything unique about your training program / syllabus. Ex: accelerated or flexible courses",
  }

  def dynamic_jsonb_form(form, jsonb_field)
    fields = ONBOARDING_FIELDS[jsonb_field]

    fields.map do |field, field_type|
      label = form.label field.to_sym, field.to_s.humanize
      subtitle = ONBOARDING_FIELD_LABELS[field] ? content_tag(:p, ONBOARDING_FIELD_LABELS[field], class: "text-sm text-gray-500 mt-1") : ""
      input = case field_type
              when :string
                form.text_field field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              when :integer
                form.number_field field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              when :email
                form.email_field field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              when :phone
                form.telephone_field field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              when :text
                form.text_area field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              when :date
                form.date_field field.to_sym, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              # Add more field types as needed
              end
      content_tag(:div, class: "my-5") do
        label + subtitle + input
      end
    end.join.html_safe
  end
end

app/views/onboardings/_form.html.erb
<%= form_with(model: [account, onboarding], class: "contents") do |form| %>
  <% if onboarding.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(onboarding.errors.count, "error") %> prohibited this onboarding from being saved:</h2>

      <ul>
        <% onboarding.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :account_id, value: account.id %>

  <% case params[:section] %>
    <% when "primary contact information" %>
      <h3 class="text-xl font-semibold mt-10">Primary Contact Information</h3>
      <%= dynamic_jsonb_form(form, :primary_contact_information) %>
    <% when "specific business information" %>
      <h3 class="text-xl font-semibold mt-10">Specific Business Information</h3>
      <%= dynamic_jsonb_form(form, :specific_business_information) %>
  <% end %>

  <div class="inline">
    <%= form.submit "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>

<% end %>

app/views/onboardings/edit.html.erb
<div class="lg:pl-72 mx-auto md:w-2/3 w-full">
  <%= render "form", account: @account, onboarding: @onboarding %>
</div>

app/views/onboardings/index.html.erb
<div class="lg:pl-72 ">
  <div class="mx-auto w-full p-5">
    <h1 class="font-bold text-4xl mb-10">Onboarding</h1>

    <%= link_to "General Business Information", edit_account_path(@account), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium w-fit" %>

    <% if @account.onboarding.present? %>
      <%= link_to 'Primary Contact Information', edit_account_onboarding_path(@account, @account.onboarding, section: "primary contact information"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium w-fit mt-5" %>
      <%= link_to 'Specific Business Information', edit_account_onboarding_path(@account, @account.onboarding, section: "specific business information"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium w-fit mt-5" %>
    <% else %>
      <%= link_to 'Primary Contact Information', new_account_onboarding_path(@account, section: "primary contact information"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium w-fit mt-5" %>
      <%= link_to 'Specific Business Information', new_account_onboarding_path(@account, section: "specific business information"), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium w-fit mt-5" %>
    <% end %>
  </div>
</div>

app/views/onboardings/new.html.erb
<div class="lg:pl-72 mx-auto md:w-2/3 w-full">
  <%= render "form", account: @account, onboarding: @onboarding %>
</div>