config/routes.rb
Rails.application.routes.draw do
  get '/sitemap.xml.gz', to: redirect("https://rrmsitemaps.s3.us-east-2.amazonaws.com/sitemap.xml.gz")

  # 404/500 pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", invitations: 'invitations' }

  root to: 'customer_portal#index'

  post 'uploader/image', to: 'uploader#image' #add upload image to notams

  authenticated :user do
    resources :users, only: [:index]
    resource :profile_image, only: [:destroy]
    resources :accounts do
      post :invite_user, on: :member
      get 'users', to: 'accounts#users', as: :users
      resources :onboardings
      resource :logo, only: [:destroy]
      resources :tickets do
        member do
          patch :update_completed
        end
        resources :comments
        resources :ticket_subscriptions, only: [:create, :destroy]
      end
    end
    resources :tickets, only: [:index], controller: 'customer_portal/tickets'
  end

  get 'locations/states', to: 'locations#states'
  get 'locations/cities', to: 'locations#cities'
end

app/models/account.rb
class Account < ApplicationRecord
  include RandomId
  
  has_many :tickets
  has_one_attached :logo
  belongs_to :account_manager, class_name: 'User', foreign_key: 'account_manager_id', optional: true
  belongs_to :lead_developer, class_name: 'User', foreign_key: 'lead_developer_id', optional: true
  has_many :account_users
  has_many :users, through: :account_users
  has_one :onboarding

  delegate :overdue, :due_today, :due_tomorrow, :due_later_this_week, :due_next_week, :due_later_within_a_month, :due_later, :no_due_date, :completed, to: :tickets, prefix: true
  delegate :user_assigned_tickets, to: :tickets

  def resized_logo
    logo.variant(resize_to_limit: [300, 300]).processed
  end

  def invite_user(user)
    account_users.create(user: user)
  end

  def countries
    CS.countries.invert
  end

  def states
    CS.states(country)&.invert || []
  end

  def cities
    CS.cities(state, country)&.invert || []
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy invite_user ]
  load_and_authorize_resource except: %i[ users ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all.includes(logo_attachment: :blob)
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def invite_user
    email = params[:email]
    user = User.find_by(email: email)

    unless user
      user = User.invite!(email: email, username: email)
    end

    @account.invite_user(user)
    redirect_to @account, notice: "Invitation sent to #{email}."
  end

  def users
    @account = Account.findr(params[:account_id])
    authorize! :read, @account
    @account_users = @account.account_users.includes(:user)
    authorize! :read, AccountUser
  end

  def onboarding
    @account = Account.findr(params[:account_id])
    authorize! :read, @account
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.findr(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :email, :phone, :website, :logo, :account_manager_id, :lead_developer_id, :address_line_1, :address_line_2, :city, :state, :zip, :country)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>" class="flex flex-col px-4 py-8 rounded-md shadow shadow-gray-400 items-center">

  <% if account.logo.attached? %>
    <%= image_tag account.resized_logo, class: "size-36 rounded-full object-contain" %>
  <% else %>
    <%= image_tag "airplane-logo.webp", class: "size-36 rounded-full object-contain" %>
  <% end %>

  <div class="flex flex-col gap-1 my-5 text-center">
    <p class="font-semibold text-2xl">
      <%= account.name %>
    </p>
    <p class="font-semibold text-gray-400">
      Location
    </p>
  </div>

  <div class="flex gap-2 flex-col 2xl:flex-row">
    <%= link_to "Go to account", account, class: "rounded-lg text-center py-3 px-5 text-blue-600 border-blue-600 border hover:bg-white hover:text-black inline-block font-medium duration-200 bg-blue-600 text-white" %>
    <%= link_to 'Edit this account', edit_account_path(account), class: "rounded-lg text-center py-3 px-5 bg-yellow-600 border border bg-yellow-600 hover:bg-white text-white hover:text-black duration-200 inline-block font-medium" %>
  </div>
</div>

app/views/accounts/_account_user.html.erb
<p><%= account_user.user.username %></p>
<p><%= account_user.user.full_name %></p>
<p><%= account_user.user.email %></p>
<p><%= account_user.role %></p>
<p><%= account_user.user.invitation_accepted_at.present? %></p>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents", data: { controller: "country-select" }) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :logo %>
    <% if account.logo.attached? %>
      <div id="<%= dom_id(account, :logo) %>">
        <%= image_tag account.logo, class: "w-1/3"  %>
        <%= link_to "Remove logo", account_logo_path(account), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>
    <% end %>
    <%= form.file_field :logo, accept: 'image/jpeg, image/png', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name, "Business Name" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email, "Business Email" %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone, "Business Phone" %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :website, "Business Website" %>
    <%= form.text_field :website, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address_line_1 %>
    <%= form.text_field :address_line_1, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address_line_2 %>
    <%= form.text_field :address_line_2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :zip, "ZIP / Postal Code" %>
    <%= form.text_field :zip, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :country %>
    <%= form.select :country, 
      [["United States", "US"]] + 
      account.countries.reject { |country_name, _| country_name == "United States" }
                        .sort_by { |country_name, _| country_name }
                        .map { |country_name, country_code| [country_name, country_code] }, 
      { include_blank: 'Select a country' }, 
      data: { country_select_target: "country", action: 'change->country-select#changeCountry' }, 
      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.select :state, 
      account.country.present? ? CS.states(account.country).map { |code, name| [name, code] } : [], # Pre-populate states if available
      { include_blank: 'Select a state', selected: account.state }, 
      data: { country_select_target: "state", action: 'change->country-select#changeState' }, 
      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.select :city, 
      account.state.present? ? CS.cities(account.state, account.country).map { |name| [name, name] } : [], # Pre-populate cities if available
      { include_blank: 'Select a city', selected: account.city }, 
      data: { country_select_target: "city" }, 
      class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if current_user.admin? %>
    <div class="my-5">
      <%= form.label :account_manager_id, "Account Manager" %><br>
      <%= form.collection_select :account_manager_id, User.all, :id, :first_name, { include_blank: "None" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :lead_developer_id, "Lead Developer" %><br>
      <%= form.collection_select :lead_developer_id, User.all, :id, :first_name, { include_blank: "None" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="lg:pl-72 ">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing account</h1>

    <%= render "form", account: @account %>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="lg:pl-72">
  <div class="p-10">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Accounts</h1>
      <%= link_to 'New account', new_account_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <div id="accounts" class="min-w-full mt-10 gap-5 grid sm:grid-cols-2 lg:grid-cols-3">
      <%= render @accounts %>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="lg:pl-72 ">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New account</h1>

    <%= render "form", account: @account %>

    <%= link_to 'Back to accounts', accounts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="lg:pl-72 ">
  <div class="mx-auto md:w-2/3 w-full flex p-10">
    <div class="mx-auto">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <h1 class="text-3xl font-semibold"><%= @account.name %> Dashboard</h1>

      <%= link_to 'Edit this account', edit_account_path(@account), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>

app/views/accounts/users.html.erb
<div class="lg:pl-72 ">
  <div class="mx-auto w-full p-5">
    <h1 class="font-bold text-4xl">Users</h1>

    <% if current_user.admin? %>
      <%= form_with url: invite_user_account_path(@account), method: :post, class: "mt-5" do %>
        <%= label_tag :email, "Email" %>
        <%= text_field_tag :email %>
        <%= submit_tag "Send Invitation", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium cursor-pointer" %>
      <% end %>
    <% end %>

    <div class="grid grid-cols-5 mt-5">
      <div class="font-bold">Username</div>
      <div class="font-bold">Full Name</div>
      <div class="font-bold">Email</div>
      <div class="font-bold">Role</div>
      <div class="font-bold">Invitation Accepted</div>
      <%= render partial: "account_user", collection: @account_users %>
    </div>
  </div>
</div>